TrainingPortal/Models/CourseViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TrainingPortal.Common.Models;

namespace TrainingPortal.Models
{
    public class CourseViewModel
    {
        public int CourseId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string TargetAudience { get; set; }

        public IEnumerable<Lesson> Lessons { get; set; }
        public IEnumerable<Test> Tests { get; set; }
    }
}

TrainingPortal/Models/LessonViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TrainingPortal.Models
{
    public class LessonViewModel
    {
        public string NameCourse { get; set; }
        public string NameLesson { get; set; }
        public string Material { get; set; }
    }
}

TrainingPortal/Models/TestViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TrainingPortal.Common.Models;

namespace TrainingPortal.Models
{
    public class TestViewModel
    {
        public int TestId { get; set; }
        public string NameCourse { get; set; }
        public string NameTest { get; set; }
        public IEnumerable<Question> Questions { get; set; }
    }
}

TrainingPortal/Controllers/LessonsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TrainingPortal.BLL.Infrastructure;
using TrainingPortal.BLL.Interfaces;
using TrainingPortal.Common.Models;

namespace TrainingPortal.Controllers
{
    [Authorize(Roles = "Editor")]
    public class LessonsController : Controller
    {
        private ILessonService lessonService;
        private ICourseService courseService;

        public LessonsController(ILessonService lessonService, ICourseService courseService)
        {
            this.lessonService = lessonService;
            this.courseService = courseService;
        }

        // GET: LessonsController
        public ActionResult Index()
        {
            return View(lessonService.GetAll());
        }

        // GET: LessonsController/Create
        public ActionResult Create()
        {
            ViewData["CourseId"] = new SelectList(courseService.GetAll(),
                   "CourseId", "Name");
            return View();
        }

        // POST: LessonsController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Lesson lesson)
        {
            try
            {
                lessonService.Create(lesson);
                return RedirectToAction(nameof(Index));
            }
            catch (ValidationException ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View(lesson);
            }
        }

        // GET: LessonsController/Edit/5
        public ActionResult Edit(int id)
        {
            ViewData["CourseId"] = new SelectList(courseService.GetAll(),
                   "CourseId", "Name");
            return View(lessonService.Get(id));
        }

        // POST: LessonsController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Lesson lesson)
        {
            try
            {
                lessonService.Update(lesson);
                return RedirectToAction(nameof(Index));
            }
            catch (ValidationException ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View(lesson);
            }
        }

        // GET: LessonsController/Delete/5
        public ActionResult Delete(int id)
        {
            return View(lessonService.Get(id));
        }

        // POST: LessonsController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(Lesson lesson)
        {
            try
            {
                lessonService.Delete(lesson.LessonId);
                return RedirectToAction(nameof(Index));
            }
            catch (ValidationException ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View(lesson);
            }
        }
    }
}

TrainingPortal/Controllers/RolesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using TrainingPortal.BLL.Infrastructure;
using TrainingPortal.BLL.Interfaces;
using TrainingPortal.Common.Models;

namespace TrainingPortal.Controllers
{
    [Authorize(Roles = "Admin")]
    public class RolesController : Controller
    {
        private IRoleService roleService;

        public RolesController(IRoleService roleService)
        {
            this.roleService = roleService;
        }

        // GET: UsersController
        public ActionResult Index()
        {
            return View(roleService.GetAllRoles());
        }

        // GET: UsersController/Details/5
        public ActionResult Details(int id)
        {
            return View(roleService.GetRole(id));
        }

        // GET: UsersController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: UsersController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Role role)
        {
            try
            {
                roleService.Create(role);
                return RedirectToAction(nameof(Index));
            }
            catch (ValidationException ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View(role);
            }
        }

        // GET: UsersController/Edit/5
        public ActionResult Edit(int id)
        {
            return View(roleService.GetRole(id));
        }

        // POST: UsersController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Role role)
        {
            try
            {
                roleService.Update(role);
                return RedirectToAction(nameof(Index));
            }
            catch (ValidationException ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View(role);
            }
        }

        // GET: UsersController/Delete/5
        public ActionResult Delete(int id)
        {
            return View(roleService.GetRole(id));
        }

        // POST: UsersController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(Role role)
        {
            try
            {
                roleService.Delete(role.RoleId);
                return RedirectToAction(nameof(Index));
            }
            catch (ValidationException ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View(role);
            }
        }
    }
}

TrainingPortal/Controllers/SectionsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TrainingPortal.BLL.Infrastructure;
using TrainingPortal.BLL.Interfaces;
using TrainingPortal.Common.Models;

namespace TrainingPortal.Controllers
{
    [Authorize(Roles = "Editor")]
    public class SectionsController : Controller
    {
        private ISectionService sectionService;

        public SectionsController(ISectionService sectionService)
        {
            this.sectionService = sectionService;
        }

        // GET: SetionsController
        public ActionResult Index()
        {
            return View(sectionService.GetAll());
        }

        // GET: SetionsController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: SetionsController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Section section)
        {
            try
            {
                sectionService.Create(section);
                return RedirectToAction(nameof(Index));
            }
            catch (ValidationException ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View(section);
            }
        }

        public ActionResult Edit(int id)
        {
            return View(sectionService.Get(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Section section)
        {
            try
            {
                sectionService.Update(section);
                return RedirectToAction(nameof(Index));
            }
            catch (ValidationException ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View(section);
            }
        }

        // GET: SetionsController/Delete/5
        public ActionResult Delete(int id)
        {
            return View(sectionService.Get(id));
        }

        // POST: SetionsController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(Section section)
        {
            try
            {
                sectionService.Delete(section.SectionId);
                return RedirectToAction(nameof(Index));
            }
            catch (ValidationException ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View(section);
            }
        }
    }
}

TrainingPortal/Controllers/TestsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TrainingPortal.BLL.Infrastructure;
using TrainingPortal.BLL.Interfaces;
using TrainingPortal.Common.Models;

namespace TrainingPortal.Controllers
{
    [Authorize(Roles = "Editor")]
    public class TestsController : Controller
    {
        private ITestService testService;
        private ICourseService courseService;

        public TestsController(ITestService testService, ICourseService courseService)
        {
            this.testService = testService;
            this.courseService = courseService;
        }
        // GET: TestsController
        public ActionResult Index()
        {
            return View(testService.GetAll());
        }

        // GET: TestsController/Create
        public ActionResult Create()
        {
            ViewData["CourseId"] = new SelectList(courseService.GetAll(),
                   "CourseId", "Name");
            return View();
        }

        // POST: TestsController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Test test)
        {
            try
            {
                testService.Create(test);
                return RedirectToAction(nameof(Index));
            }
            catch (ValidationException ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View(test);
            }
        }

        // GET: TestsController/Edit/5
        public ActionResult Edit(int id)
        {
            ViewData["CourseId"] = new SelectList(courseService.GetAll(),
                   "CourseId", "Name");
            return View(testService.Get(id));
        }

        // POST: TestsController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Test test)
        {
            try
            {
                testService.Update(test);
                return RedirectToAction(nameof(Index));
            }
            catch (ValidationException ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View(test);
            }
        }

        // GET: TestsController/Delete/5
        public ActionResult Delete(int id)
        {
            return View(testService.Get(id));
        }

        // POST: TestsController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(Test test)
        {
            try
            {
                testService.Delete(test.TestId);
                return RedirectToAction(nameof(Index));
            }
            catch (ValidationException ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View(test);
            }
        }
    }
}

TrainingPortal/Controllers/UserRolesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TrainingPortal.BLL.Infrastructure;
using TrainingPortal.BLL.Interfaces;
using TrainingPortal.Common.Models;

namespace TrainingPortal.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UserRolesController : Controller
    {
        private IUserRolesService userRolesService;

        public UserRolesController(IUserRolesService userRolesService)
        {
            this.userRolesService = userRolesService;
        }

        // GET: UserRolesController
        public ActionResult Index()
        {
            return View(userRolesService.GetAll());
        }

        // GET: UserRolesController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: UserRolesController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(UserRole userRole)
        {
            try
            {
                userRolesService.Create(userRole.UserId, userRole.RoleId);
                return RedirectToAction(nameof(Index));
            }
            catch (ValidationException ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View(userRole);
            }
        }

        // GET: UserRolesController/Delete/5
        public ActionResult Delete(int userId, int roleId)
        {
            return View(new UserRole(userId, roleId));
        }

        // POST: UserRolesController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(UserRole userRole)
        {
            try
            {
                userRolesService.Delete(userRole.UserId, userRole.RoleId);
                return RedirectToAction(nameof(Index));
            }
            catch (ValidationException ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View(userRole);
            }
        }
    }
}

TrainingPortal/Controllers/UsersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TrainingPortal.BLL.Infrastructure;
using TrainingPortal.BLL.Interfaces;
using TrainingPortal.Common.Models;

namespace TrainingPortal.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UsersController : Controller
    {
        private IUserService userService;

        public UsersController(IUserService userService)
        {
            this.userService = userService;
        }

        // GET: UsersController
        public ActionResult Index()
        {
            return View(userService.GetUsers());
        }

        // GET: UsersController/Details/5
        public ActionResult Details(int id)
        {
            return View(userService.Get(id));
        }

        // GET: UsersController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: UsersController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(User user)
        {
            try
            {
                userService.Create(user);
                return RedirectToAction(nameof(Index));
            }
            catch (ValidationException ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View(user);
            }
        }

        // GET: UsersController/Edit/5
        public ActionResult Edit(int id)
        {
            return View(userService.Get(id));
        }

        // POST: UsersController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(User user)
        {
            try
            {
                userService.Update(user);
                return RedirectToAction(nameof(Index));
            }
            catch (ValidationException ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View(user);
            }
        }

        // GET: UsersController/Delete/5
        public ActionResult Delete(int id)
        {
            return View(userService.Get(id));
        }

        // POST: UsersController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(User user)
        {
            try
            {
                userService.Delete(user.UserId);
                return RedirectToAction(nameof(Index));
            }
            catch (ValidationException ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View(user);
            }
        }
    }
}

TrainingPortal/Views/Home/Course.cshtml
@model CourseViewModel

@{
    ViewData["Title"] = "CourseViewModel";
}

@{
    ViewData["Title"] = "CourseViewModel";
}

<h1>Название курса: @Model.Name</h1>
<h4>Описание: @Model.Description </h4>
<h4>Аудитория: @Model.TargetAudience </h4>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.Name("Название урока")
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Lessons)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.NameLesson)
                <td>
                    @Html.ActionLink("Смотреть", "Lessons", new { id = item.LessonId })
                </td>
            </tr>
        }
    </tbody>
</table>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.Name("Название теста")
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Tests)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.NameTest)
                </td>
                <td>
                    @Html.ActionLink("Пройти тест", "Tests", new { id = item.TestId })
                </td>
            </tr>
        }
    </tbody>
</table>

TrainingPortal/Views/Home/Courses.cshtml
@model IEnumerable<TrainingPortal.Common.Models.Course>

@{
    ViewData["Title"] = "Courses";
}

@{
    ViewData["Title"] = "Courses";
}

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TargetAudience)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TargetAudience)
            </td>
            <td>
                @Html.ActionLink("Узнать больше", "Course", new { id = item.CourseId })
            </td>
        </tr>
        }
    </tbody>
</table>

TrainingPortal/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p><a asp-action="TestAut">TestAut</a>.</p>
    <p><a asp-action="TestRole">TestRole</a>.</p>
    <p><a asp-controller="Users" asp-action="Index">Users</a>.</p>
    <p><a asp-controller="Roles" asp-action="Index">Roles</a>.</p>
    <p><a asp-controller="UserRoles" asp-action="Index">UserRoles</a>.</p>
</div>

TrainingPortal/Views/Home/Lessons.cshtml
@model LessonViewModel

@{
    ViewData["Title"] = "Lessons";
}

<h1>Курс: @Model.NameCourse</h1>
<br />
<br />
<div>
    <h4>Название урока: @Model.NameLesson</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Material)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Material)
        </dd>
    </dl>
</div>

TrainingPortal/Views/Home/MyCourses.cshtml
@model IEnumerable<TrainingPortal.Common.Models.Course>

@{
    ViewData["Title"] = "MyCourses";
}

@{
    ViewData["Title"] = "MyCourses";
}

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.Name("Пройденные курсы")
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.ActionLink("Скачать сертификат", "GetCertificate", new { courseId = item.CourseId })
                </td>
            </tr>
        }
    </tbody>
</table>

TrainingPortal/Views/Home/Result.cshtml
@model ResultTestViewModel

@{
    ViewData["Title"] = "ResultTest";
}

<h1>Курс: @Model.Course.NameCourse</h1>
<h4>Тест: @Model.Test.NameTest</h4>
<h4>Прогрес по курсу: @Model.Course.Result</h4>
<h4>Результат теста: @Model.Test.Result</h4>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.Name("Вопрос")
            </th>
            <th>
                @Html.Name("Ваш ответ")
            </th>
            <th>
                @Html.Name("Результат")
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Test.ValidatedQuestions)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Question.QuestionText)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Answer)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Result)
                </td>
            </tr>
        }
    </tbody>
</table>

TrainingPortal/Views/Home/Search.cshtml
@{
    ViewData["Title"] = "Search";
}

<h1>Search courses</h1>

<h4>Course</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div class="form-group">
                <label name="nameCourse" class="control-label">Курс</label>
                <input name="nameCourse" class="form-control" />
            </div>
            <div class="form-group">
                <label name="nameSection" class="control-label">Раздел</label>
                <input name="nameSection" class="form-control" />
            </div>
            <div class="form-group">
                <label name="targetAudience" class="control-label">Аудитория</label>
                <input name="targetAudience" class="form-control" />
            </div>
            <div class="form-group">
                <input type="submit" asp-action="Search" value="Поиск" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Главная</a>
</div>

TrainingPortal/Views/Home/Sections.cshtml
@model IEnumerable<TrainingPortal.Common.Models.Section>

@{
    ViewData["Title"] = "Sections";
}

<h1>Разделы</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.ActionLink("Перейти к курсам", "Courses", new { sectionId = item.SectionId })
            </td>
        </tr>
}
    </tbody>
</table>

TrainingPortal/Views/Home/Tests.cshtml
@model TestViewModel

@{
    ViewData["Title"] = "Tests";
}

<h1>Название курса: @Model.NameCourse</h1>
<h4>Тест: @Model.NameTest </h4>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            @foreach (Question question in Model.Questions)
            {
            <div class="form-group">
                <label class="control-label">@question.QuestionText</label>
                <input id="results" name="results" class="form-control" />
            </div>
            }
        <div class="form-group">
            <input asp-for="TestId" type="hidden" />
            <input type="submit" asp-action="Result" value="Отправить результат" class="btn btn-primary" />
        </div>
        </form>
    </div>
</div>